// <auto-generated />
namespace BestApp.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SetNamelenght : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetNamelenght));
        
        string IMigrationMetadata.Id
        {
            get { return "201411140959206_Set Name lenght"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
